/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author id107
 */
public class hesap_maknsi extends javax.swing.JFrame {

    /**
     * Creates new form hesap_maknsi
     */
    public hesap_maknsi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField_gosterge = new javax.swing.JTextField();
        jButton_0 = new javax.swing.JButton();
        jButton_MC = new javax.swing.JButton();
        jButton_MR = new javax.swing.JButton();
        jButton_MS = new javax.swing.JButton();
        jButton_MARTI = new javax.swing.JButton();
        jButton_MESKİ = new javax.swing.JButton();
        jButton_sagdansil = new javax.swing.JButton();
        jButtonCE = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButton_artieksi = new javax.swing.JButton();
        jButton_karekok = new javax.swing.JButton();
        jButton_7 = new javax.swing.JButton();
        jButton_8 = new javax.swing.JButton();
        jButton_9 = new javax.swing.JButton();
        jButton_bol = new javax.swing.JButton();
        jButton_mod = new javax.swing.JButton();
        jButton_1 = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        jButton_cikar = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton_6 = new javax.swing.JButton();
        jButton_carp = new javax.swing.JButton();
        jButton_1bolux = new javax.swing.JButton();
        jButton_virgul = new javax.swing.JButton();
        jButton_topla = new javax.swing.JButton();
        jButton_esittir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton7.setText("jButton1");

        jButton17.setText("jButton1");

        jButton18.setText("jButton1");

        jButton19.setText("jButton1");

        jButton30.setText("jButton1");

        jButton29.setText("jButton1");

        jButton50.setText("MC");

        jButton51.setText("MC");

        jButton52.setText("MC");

        jButton53.setText("MC");

        jButton54.setText("MC");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hesap Makinesi");

        jTextField_gosterge.setEditable(false);
        jTextField_gosterge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_gosterge.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_gosterge.setText("0");
        jTextField_gosterge.setEnabled(false);

        jButton_0.setText("0");
        jButton_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_0ActionPerformed(evt);
            }
        });

        jButton_MC.setText("MC");
        jButton_MC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MCActionPerformed(evt);
            }
        });

        jButton_MR.setText("MR");
        jButton_MR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MRActionPerformed(evt);
            }
        });

        jButton_MS.setText("MS");
        jButton_MS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MSActionPerformed(evt);
            }
        });

        jButton_MARTI.setText("M+");
        jButton_MARTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MARTIActionPerformed(evt);
            }
        });

        jButton_MESKİ.setText("M-");
        jButton_MESKİ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MESKİActionPerformed(evt);
            }
        });

        jButton_sagdansil.setText("<-");
        jButton_sagdansil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sagdansilActionPerformed(evt);
            }
        });

        jButtonCE.setText("CE");
        jButtonCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCEActionPerformed(evt);
            }
        });

        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButton_artieksi.setText("+-");
        jButton_artieksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_artieksiActionPerformed(evt);
            }
        });

        jButton_karekok.setText("_/");
        jButton_karekok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_karekokActionPerformed(evt);
            }
        });

        jButton_7.setText("7");
        jButton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_7ActionPerformed(evt);
            }
        });

        jButton_8.setText("8");
        jButton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_8ActionPerformed(evt);
            }
        });

        jButton_9.setText("9");
        jButton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_9ActionPerformed(evt);
            }
        });

        jButton_bol.setText("/");
        jButton_bol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bolActionPerformed(evt);
            }
        });

        jButton_mod.setText("%");
        jButton_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modActionPerformed(evt);
            }
        });

        jButton_1.setText("1");
        jButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1ActionPerformed(evt);
            }
        });

        jButton_2.setText("2");
        jButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2ActionPerformed(evt);
            }
        });

        jButton_3.setText("3");
        jButton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_3ActionPerformed(evt);
            }
        });

        jButton_cikar.setText("-");
        jButton_cikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cikarActionPerformed(evt);
            }
        });

        jButton_4.setText("4");
        jButton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4ActionPerformed(evt);
            }
        });

        jButton_5.setText("5");
        jButton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5ActionPerformed(evt);
            }
        });

        jButton_6.setText("6");
        jButton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_6ActionPerformed(evt);
            }
        });

        jButton_carp.setText("*");
        jButton_carp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_carpActionPerformed(evt);
            }
        });

        jButton_1bolux.setText("1/x");
        jButton_1bolux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1boluxActionPerformed(evt);
            }
        });

        jButton_virgul.setText(",");
        jButton_virgul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_virgulActionPerformed(evt);
            }
        });

        jButton_topla.setText("+");
        jButton_topla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_toplaActionPerformed(evt);
            }
        });

        jButton_esittir.setText("=");
        jButton_esittir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_esittirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_gosterge, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_bol, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton_sagdansil, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonCE, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_artieksi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_karekok, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_carp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton_virgul, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton_cikar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton_topla, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_1bolux, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_esittir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton_MC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_MR, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_MS, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_MARTI, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_MESKİ, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_gosterge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_MC)
                    .addComponent(jButton_MR)
                    .addComponent(jButton_MS)
                    .addComponent(jButton_MARTI)
                    .addComponent(jButton_MESKİ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_sagdansil)
                    .addComponent(jButtonCE)
                    .addComponent(jButtonC)
                    .addComponent(jButton_artieksi)
                    .addComponent(jButton_karekok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_7)
                    .addComponent(jButton_8)
                    .addComponent(jButton_9)
                    .addComponent(jButton_bol)
                    .addComponent(jButton_mod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_4)
                    .addComponent(jButton_5)
                    .addComponent(jButton_6)
                    .addComponent(jButton_carp)
                    .addComponent(jButton_1bolux))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_1)
                            .addComponent(jButton_2)
                            .addComponent(jButton_3)
                            .addComponent(jButton_cikar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton_virgul)
                                .addComponent(jButton_topla))))
                    .addComponent(jButton_esittir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_0ActionPerformed
            
        rakamekle("0");
        
    }//GEN-LAST:event_jButton_0ActionPerformed

    private void jButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1ActionPerformed
       
        rakamekle("1");
        
        
    }//GEN-LAST:event_jButton_1ActionPerformed
    
    String hafiza= "", islem="";
    void islem(String i) {
              
        
    }
    
    
    
    void rakamekle (String s){
           String deger = jTextField_gosterge.getText();
          if(deger.compareTo("0")>0) {
          jTextField_gosterge.setText(deger.concat(s));   
        
          }else { 
              jTextField_gosterge.setText("");
              jTextField_gosterge.setText(s);
          }
     

//  String deger = jTextField_gosterge.getText();
//  jTextField_gosterge.setText("");
//         jTextField_gosterge.setText(s);

     }
    
    
    private void jButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2ActionPerformed

           rakamekle("2");
                  
    }//GEN-LAST:event_jButton_2ActionPerformed

    private void jButton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_3ActionPerformed
      
      
    rakamekle("3")  ;
          
        
    }//GEN-LAST:event_jButton_3ActionPerformed

    private void jButton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4ActionPerformed
        
          rakamekle("4");
        
        
    }//GEN-LAST:event_jButton_4ActionPerformed

    private void jButton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5ActionPerformed
   
           rakamekle("5");
        
    }//GEN-LAST:event_jButton_5ActionPerformed

    private void jButton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_6ActionPerformed

          rakamekle("6");
         
        
        
    }//GEN-LAST:event_jButton_6ActionPerformed

    private void jButton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_7ActionPerformed
        
        rakamekle("7");
        
    }//GEN-LAST:event_jButton_7ActionPerformed

    private void jButton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_8ActionPerformed
       
         rakamekle("8");
        
    }//GEN-LAST:event_jButton_8ActionPerformed

    private void jButton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_9ActionPerformed
      
          rakamekle("9");
        
    }//GEN-LAST:event_jButton_9ActionPerformed

    private void jButton_toplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_toplaActionPerformed
        hafiza = jTextField_gosterge.getText();
        jTextField_gosterge.setText("");
        islem ="+";
        
    }//GEN-LAST:event_jButton_toplaActionPerformed

    private void jButton_esittirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_esittirActionPerformed
       
        double sonuc=0;
        
        
   if(islem.compareTo("+")==0) {
 sonuc = Double.parseDouble(hafiza) + Integer.parseInt(jTextField_gosterge.getText());
    // jTextField_gosterge.setText(String.valueOf(sonuc));
         
        }
   
   else if (islem.compareTo("-")==0){
        sonuc = Double.parseDouble(hafiza) - Integer.parseInt(jTextField_gosterge.getText());
     // jTextField_gosterge.setText(String.valueOf(sonuc));
             
   }
   else if (islem.compareTo("*")==0) {
       
        sonuc = Double.parseDouble(hafiza) * Integer.parseInt(jTextField_gosterge.getText());
 //    jTextField_gosterge.setText(String.valueOf(sonuc));
              
   }
    else if (islem.compareTo("/")==0 ) {
       
        sonuc = Double.parseDouble(hafiza) / Integer.parseInt(jTextField_gosterge.getText());
        
    // jTextField_gosterge.setText(String.valueOf(sonuc));
    
    
             
   }
   String s = String.valueOf(sonuc);
   
//   if((s.substring(s.length()-2, s.length())).compareTo(".0")==0) {
//     s = s.substring(0,s.length()-2);
//     
     
   // }
   
  if( s.endsWith(".0")) {
        
        s = s.substring(0, s.length() -2);
        
    }
   
    jTextField_gosterge.setText(s);
    }//GEN-LAST:event_jButton_esittirActionPerformed

    
    
    
    private void jButton_cikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cikarActionPerformed

 hafiza = jTextField_gosterge.getText();
        jTextField_gosterge.setText("");
        islem ="-";
        
    }//GEN-LAST:event_jButton_cikarActionPerformed

    private void jButton_carpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_carpActionPerformed
        
       hafiza = jTextField_gosterge.getText();
        jTextField_gosterge.setText("");
        islem ="*"; 
        
    }//GEN-LAST:event_jButton_carpActionPerformed

    private void jButton_bolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bolActionPerformed
     
      hafiza = jTextField_gosterge.getText();
        jTextField_gosterge.setText("");
        islem ="/";  
        
    }//GEN-LAST:event_jButton_bolActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
    
        islem = "";
        jTextField_gosterge.setText("0");
        hafiza = "";
        
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCEActionPerformed

        
         jTextField_gosterge.setText("0");
        
        
    }//GEN-LAST:event_jButtonCEActionPerformed

    private void jButton_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modActionPerformed
        // TODO add your handling code here:
        
         
        
        
    }//GEN-LAST:event_jButton_modActionPerformed

    private void jButton_karekokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_karekokActionPerformed
        // TODO add your handling code here:
        double sonuc = Double.parseDouble(jTextField_gosterge.getText());
        
        sonuc = Math.sqrt(sonuc);
        String s = String.valueOf(sonuc);
        if( s.endsWith(".0")) {
        
        s = s.substring(0, s.length() -2);
        
    }
        jTextField_gosterge.setText(s);
        
        
        
    }//GEN-LAST:event_jButton_karekokActionPerformed

    
    
    
    private void jButton_artieksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_artieksiActionPerformed
        // TODO add your handling code here:
        String s = jTextField_gosterge.getText();
        
        
      if(jTextField_gosterge.getText().startsWith("-")) {
          
          s = s.substring(1, s.length());
          
          
      }else {
          s = "-" +s;
          
      }
       jTextField_gosterge.setText(s);
        
        
    }//GEN-LAST:event_jButton_artieksiActionPerformed

    private void jButton_sagdansilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sagdansilActionPerformed

        if(jTextField_gosterge.getText().length()> 0) {
        
jTextField_gosterge.setText(jTextField_gosterge.getText().substring(0,jTextField_gosterge.getText().length()-1));

        }
        else {
            jTextField_gosterge.setText("0");
            
            
        }


    }//GEN-LAST:event_jButton_sagdansilActionPerformed

    private void jButton_1boluxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1boluxActionPerformed
        // TODO add your handling code here:
          double sonuc = Double.parseDouble(jTextField_gosterge.getText());
        
        sonuc = 1/sonuc;
        String s = String.valueOf(sonuc);
        if( s.endsWith(".0")) {
        
        s = s.substring(0, s.length() -2);
        
    }
        jTextField_gosterge.setText(s);
        
        
        
    }//GEN-LAST:event_jButton_1boluxActionPerformed

    private void jButton_MCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MCActionPerformed
        // TODO add your handling code here:
        
       M = 0;
       jLabel1.setText("");
        
    }//GEN-LAST:event_jButton_MCActionPerformed

    private void jButton_MRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MRActionPerformed
        // TODO add your handling code here:
        String s = String.valueOf(M);
        if (s.endsWith(".0")) {
            
            s = s.substring(0, s.length() - 2 );
        }
        jTextField_gosterge.setText(s);
        
        
        
        
    }//GEN-LAST:event_jButton_MRActionPerformed
double M = 0;

    private void jButton_MSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MSActionPerformed
        // TODO add your handling code here:
        
        if(Double.parseDouble(jTextField_gosterge.getText())!= 0) {
        
        
        M = Double.parseDouble(jTextField_gosterge.getText());
        jLabel1.setText("M");
        }
        
        
    }//GEN-LAST:event_jButton_MSActionPerformed

    private void jButton_MARTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MARTIActionPerformed
        // TODO add your handling code here:
        
        M += Double.parseDouble(jTextField_gosterge.getText());
         jLabel1.setText("M");
        
        
        
    }//GEN-LAST:event_jButton_MARTIActionPerformed

    private void jButton_MESKİActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MESKİActionPerformed
        // TODO add your handling code here:
        
           M -= Double.parseDouble(jTextField_gosterge.getText());
         jLabel1.setText("M");
        
    }//GEN-LAST:event_jButton_MESKİActionPerformed
boolean virgül = false;

    private void jButton_virgulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_virgulActionPerformed
       
        if(virgül || jTextField_gosterge.getText().indexOf(".")>0) {
             virgül = false;
             
        }else {
           jTextField_gosterge.setText(jTextField_gosterge.getText()+ ".");
           virgül = true;
             
        }
        
        
        
        
    }//GEN-LAST:event_jButton_virgulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hesap_maknsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hesap_maknsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hesap_maknsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hesap_maknsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hesap_maknsi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonCE;
    private javax.swing.JButton jButton_0;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_1bolux;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_6;
    private javax.swing.JButton jButton_7;
    private javax.swing.JButton jButton_8;
    private javax.swing.JButton jButton_9;
    private javax.swing.JButton jButton_MARTI;
    private javax.swing.JButton jButton_MC;
    private javax.swing.JButton jButton_MESKİ;
    private javax.swing.JButton jButton_MR;
    private javax.swing.JButton jButton_MS;
    private javax.swing.JButton jButton_artieksi;
    private javax.swing.JButton jButton_bol;
    private javax.swing.JButton jButton_carp;
    private javax.swing.JButton jButton_cikar;
    private javax.swing.JButton jButton_esittir;
    private javax.swing.JButton jButton_karekok;
    private javax.swing.JButton jButton_mod;
    private javax.swing.JButton jButton_sagdansil;
    private javax.swing.JButton jButton_topla;
    private javax.swing.JButton jButton_virgul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_gosterge;
    // End of variables declaration//GEN-END:variables
}
