
import javax.swing.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author id107
 */
public class gp_14_04 extends javax.swing.JFrame {

    /**
     * Creates new form gp_14_04
     */
    public gp_14_04() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton_bilgi = new javax.swing.JButton();
        jButton_uyari = new javax.swing.JButton();
        jButton_hata = new javax.swing.JButton();
        jButton_plain = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel_cevap = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton_in1 = new javax.swing.JButton();
        jButton_in2 = new javax.swing.JButton();
        jButton_in3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_bilgi.setText("bilgi");
        jButton_bilgi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bilgiActionPerformed(evt);
            }
        });

        jButton_uyari.setText("uyarı");
        jButton_uyari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_uyariActionPerformed(evt);
            }
        });

        jButton_hata.setText("hata");
        jButton_hata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_hataActionPerformed(evt);
            }
        });

        jButton_plain.setText("plain");
        jButton_plain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_plainActionPerformed(evt);
            }
        });

        jButton2.setText("soru");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel_cevap.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_bilgi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_plain, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_hata, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_uyari, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel_cevap, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_bilgi)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_uyari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_hata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_plain))
                    .addComponent(jLabel_cevap, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("mesajlar", jPanel1);

        jButton_in1.setText("input1");
        jButton_in1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_in1ActionPerformed(evt);
            }
        });

        jButton_in2.setText("input2");
        jButton_in2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_in2ActionPerformed(evt);
            }
        });

        jButton_in3.setText("input3");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_in1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_in2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_in3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_in1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_in2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_in3)
                    .addComponent(jLabel4))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("inputlar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jTabbedPane1)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_bilgiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bilgiActionPerformed
        // TODO add your handling code here:
        
        String mesaj = "Bu bir bilgi mesajıdır.";
        String baslik ="mesaj başlığı";
        JOptionPane.showMessageDialog(this, "Bu bir bilgi mesajıdır.",baslik,JOptionPane.INFORMATION_MESSAGE);
        
        JOptionPane.showMessageDialog(this, mesaj,baslik,JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jButton_bilgiActionPerformed

    private void jButton_uyariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_uyariActionPerformed
        // TODO add your handling code here:
        
         JOptionPane.showMessageDialog(this, "Uyarı mesajı","baslik",JOptionPane.WARNING_MESSAGE);
        
        
    }//GEN-LAST:event_jButton_uyariActionPerformed

    private void jButton_hataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_hataActionPerformed
   
        
        JOptionPane.showMessageDialog(this, "hata mesajı","hata",JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_jButton_hataActionPerformed

    private void jButton_plainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_plainActionPerformed
       
        
     JOptionPane.showMessageDialog(this, "simgesiz mesaj ","plain",JOptionPane.PLAIN_MESSAGE);   
    }//GEN-LAST:event_jButton_plainActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        Object [] secenekler = {81,27,39};
 int n = JOptionPane.showOptionDialog(this, "Soru mesajı ","Soru",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,null,secenekler,secenekler[2]);
      
 if(n>=0){
      jLabel_cevap.setText("n:"+n+"-"+secenekler[n]);
 }else 
   jLabel_cevap.setText("Seçim Yapılmadı");
        
        JOptionPane.showConfirmDialog(this, "Onay veriyor musunuz?","onay",JOptionPane.YES_NO_OPTION);
  int secim= JOptionPane.showConfirmDialog(this, "Onay veriyor musunuz?","onay",JOptionPane.YES_NO_CANCEL_OPTION);
  jLabel_cevap.setText(String.valueOf(secim));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_in1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_in1ActionPerformed
        // TODO add your handling code here:
       Object [] secenekler = {"a","b","c"}; 
       String s = (String)JOptionPane.showInputDialog(this, "seçiminiz","başlık",JOptionPane.PLAIN_MESSAGE,null,secenekler,secenekler[1]);
       jLabel2.setText(s);
        
        
    }//GEN-LAST:event_jButton_in1ActionPerformed

    private void jButton_in2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_in2ActionPerformed
        // TODO add your handling code here:
         Object [] secenekler = {"araba","bisiklet","motor"}; 
       String s = (String)JOptionPane.showInputDialog(this, "seçiminiz","başlık",JOptionPane.PLAIN_MESSAGE,null,secenekler,secenekler[1]);
       jLabel3.setText(s);
        
        
    }//GEN-LAST:event_jButton_in2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gp_14_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gp_14_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gp_14_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gp_14_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gp_14_04().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_bilgi;
    private javax.swing.JButton jButton_hata;
    private javax.swing.JButton jButton_in1;
    private javax.swing.JButton jButton_in2;
    private javax.swing.JButton jButton_in3;
    private javax.swing.JButton jButton_plain;
    private javax.swing.JButton jButton_uyari;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_cevap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
