/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author id107
 */
public class gp_24_03 extends javax.swing.JFrame {

    /**
     * Creates new form gp_24_03
     */
    public gp_24_03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        Txt_f_sonuc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_topla = new javax.swing.JButton();
        jButton_cıkar = new javax.swing.JButton();
        jButton_carp = new javax.swing.JButton();
        jButton_bol = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        Txt_f_sonuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_f_sonucActionPerformed(evt);
            }
        });

        jLabel1.setText("=");

        jButton_topla.setText("+");
        jButton_topla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_toplaActionPerformed(evt);
            }
        });

        jButton_cıkar.setText("-");
        jButton_cıkar.setActionCommand("");
        jButton_cıkar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cıkarActionPerformed(evt);
            }
        });

        jButton_carp.setText("*");
        jButton_carp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_carpActionPerformed(evt);
            }
        });

        jButton_bol.setText("/");
        jButton_bol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bolActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jCheckBox1.setText("Geçmişi düzenle");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1İtemStateChanged(evt);
            }
        });
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseExited(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jCheckBox1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jCheckBox1VetoableChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Txt_f_sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_topla, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_cıkar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_carp, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_bol, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_f_sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_cıkar)
                        .addComponent(jCheckBox1))
                    .addComponent(jButton_topla, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_carp)
                    .addComponent(jButton_bol))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_f_sonucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_f_sonucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_f_sonucActionPerformed

    private void jButton_toplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_toplaActionPerformed
        // TODO add your handling code here:
        
        try {
            
       double sonuc = Double.parseDouble(jTextField1.getText())+
               Double.parseDouble(jTextField2.getText());
             
    Txt_f_sonuc.setText(String.valueOf(sonuc));
    
//      jTextArea1.setText(jTextArea1.getText()Double.parseDouble(jTextField1.getText())+" + "
//               +Double.parseDouble(jTextField2.getText())
//                +" = " + sonuc+"\n");
    
    jTextArea1.append(Double.parseDouble(jTextField1.getText())+" + "
            +Double.parseDouble(jTextField2.getText())
            +" = " + sonuc+"\n");
    
    }//GEN-LAST:event_jButton_toplaActionPerformed
  catch (Exception e) {
        jTextField1.setText("");
       jTextField2.setText("");   
       Txt_f_sonuc.setText("tekrar deneyiniz");
        }
    }
    private void jButton_cıkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cıkarActionPerformed
        // TODO add your handling code here:
        
         try {
            
       double sonuc = Double.parseDouble(jTextField1.getText())-
               Double.parseDouble(jTextField2.getText());
             
    Txt_f_sonuc.setText(String.valueOf(sonuc));
    
     jTextArea1.append(Double.parseDouble(jTextField1.getText())+" - "
            +Double.parseDouble(jTextField2.getText())
            +" = " + sonuc+"\n");
    
    }                                             
  catch (Exception e) {
        jTextField1.setText("");
       jTextField2.setText("");   
       Txt_f_sonuc.setText("tekrar deneyiniz");
        }
        
    }//GEN-LAST:event_jButton_cıkarActionPerformed

    private void jButton_carpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_carpActionPerformed
        // TODO add your handling code here:
        
            try {
            
       double sonuc = Double.parseDouble(jTextField1.getText())*
               Double.parseDouble(jTextField2.getText());
             
    Txt_f_sonuc.setText(String.valueOf(sonuc));
    
    jTextArea1.append(Double.parseDouble(jTextField1.getText())+" * "
            +Double.parseDouble(jTextField2.getText())
            +" = " + sonuc+"\n");
    
    }                                             
  catch (Exception e) {
        jTextField1.setText("");
       jTextField2.setText("");   
       Txt_f_sonuc.setText("tekrar deneyiniz");
        }
         
    }//GEN-LAST:event_jButton_carpActionPerformed

    private void jButton_bolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bolActionPerformed
        // TODO add your handling code here:
            try {
            
       double sonuc = Double.parseDouble(jTextField1.getText())/
               Double.parseDouble(jTextField2.getText());
             
    Txt_f_sonuc.setText(String.valueOf(sonuc));
    
    jTextArea1.append(Double.parseDouble(jTextField1.getText())+" / "
            +Double.parseDouble(jTextField2.getText())
            +" = " + sonuc+"\n");
    
    }                                             
  catch (Exception e) {
        jTextField1.setText("");
       jTextField2.setText("");   
       Txt_f_sonuc.setText("tekrar deneyiniz");
        }
    }//GEN-LAST:event_jButton_bolActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCheckBox1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1İtemStateChanged
        // TODO add your handling code here:
        
        if(jCheckBox1.isSelected()){
            jTextArea1.setEditable(true);
        }else{
            jTextArea1.setEditable(false);
        }
        
    }//GEN-LAST:event_jCheckBox1İtemStateChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1MouseEntered

    private void jCheckBox1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1MouseExited

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jCheckBox1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jCheckBox1VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1VetoableChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gp_24_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gp_24_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gp_24_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gp_24_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gp_24_03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txt_f_sonuc;
    private javax.swing.JButton jButton_bol;
    private javax.swing.JButton jButton_carp;
    private javax.swing.JButton jButton_cıkar;
    private javax.swing.JButton jButton_topla;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
